language: cpp
matrix:
  include:
  - os: osx
    osx_image: xcode7.2
    before_install:
    - brew install cmake
    - brew install qt5
    - brew link qt5 --force
    script:
    - mkdir build
    - cd build && cmake ..
    - cd build && make
    - ls build

